/*! 

\mainpage Source code to MDMOL and a few other documents

\section intro Introduction

The code mdmol performs molecular dynamics simulation

\section install Installation

Once you have the source files the standard

./configure

make

should generate an executable mdmol in the top level 
directory.  If not - let me know

\section examples

There are several examples in the examples directory.

These include simple lennard-jones examples
as well as a toriod example.

lets us try <br>
some formating <br>
and page breaks <br>

How about extermal references? 
<a href="http://www.cmm.upenn.edu/~moore"> moore home page </a>

*/
